name: MacOS Homebrew Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run:  brew update; brew tap cyclone-scheme/cyclone ; brew -v install cyclone-scheme/cyclone/cyclone-bootstrap
    - name: test
      run: ls -d /usr/local/share/cyclone/* && ls /usr/local/share/cyclone/cyclone/* ; cd tests; cyclone unit-tests.scm ; ./unit-tests && winds && cyclone threading.scm && ./threading && cyclone base.scm && ./base && cyclone test.scm && ./test
