name: MacOS Homebrew Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run:  brew update; brew tap cyclone-scheme/cyclone ; brew -v install cyclone-scheme/cyclone/cyclone-bootstrap
    - name: test
      run: cyclone tests/unit-tests.scm ; ./tests/unit-tests
