name: CI Windows MSYS2 (Test #2)

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [64]
#        arch: [32, 64]
    steps:
      - uses: actions/checkout@v1
      - uses: numworks/setup-msys2@v1
      - run: msys2do uname -a
      - name: Pacman
        run: msys2do pacman --noconfirm -S gcc make autoconf git
      - name: Build
        run: msys2do ./setup.mysys.sh
