name: CI

on: [fork]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ck
      run: sudo apt-get install libck-dev
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: make test
      run: make test
