name: Test Brew

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run:  make -v; brew update; brew tap cyclone-scheme/cyclone ; brew -v install cyclone-scheme/cyclone/cyclone-bootstrap
      continue-on-error: true
    - name: logs
      run: ls -l * ; ls -l libs/* ; cat /Users/runner/Library/Logs/Homebrew/cyclone-bootstrap/01.make ; cat /Users/runner/Library/Logs/Homebrew/cyclone-bootstrap/00.options.out ; cat /Users/runner/Library/Logs/Homebrew/cyclone-bootstrap/01.make.cc ; cat Makefile
    - name: test
      run: cyclone unit-tests.scm ; ./unit-tests 
