name: Test MacOS

on: [fork]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ck
      run:  brew update; brew install -v concurrencykit;
    - name: make
      run: make PREFIX=tmp ; make PREFIX=tmp install
    - name: test
      run: ./cyclone -d unit-tests.scm ; make PREFIX=tmp test
